<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Добавить',
    'Add Datetime' => 'Добавить дату и время',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Attachments' => 'Вложения',
    'Close' => 'Закрыть',
    'Delete' => 'Удалить',
    'Deleted' => 'Удалено',
    'Download' => 'Скачать',
    'Drag&Drop a file here, upload will start automatically' => 'Перетащите сюда файл, загрузка начнется автоматически',
    'Drag&Drop file here' => 'Перетащите файл сюда',
    'File Name' => 'Имя файла',
    'File deleted' => 'Файл удален',
    'File not uploaded.' => 'Файл не загружен.',
    'Forbidden file type' => 'Запрещенный тип файла',
    'ID' => 'ID',
    'Insert DB record failed' => 'Не удалось вставить запись DB.',
    'Model ID' => 'Model ID',
    'Model Name' => 'Model Name',
    'No results found.' => 'Результатов не найдено.',
    'Notes' => 'Примечания',
    'The requested file does not exist.' => 'Запрошенный файл не существует.',
    'The uploaded file does not exist.' => 'Загруженный файл не существует.',
    'Type ID' => 'Type ID',
    'UploadHandler mandatory option file_name is not set' => '',
    'UploadHandler mandatory option model_id is not set' => '',
    'UploadHandler mandatory option module_name is not set' => '',
    'User ID' => '',
    'mandatory POST parameter model_name is not set' => '',
    'upload_file is not set' => '',
    'You don\'t have access to parent record' => 'У вас нет доступа к родительской записи',
];
