<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File not uploaded.' => 'Fails netika augšuplādēts',
    'Forbidden file type' => 'Neatļauts faila tips',
    'ID' => '',
    'Insert DB record failed' => 'Neizdevās izveidot datubāzes ierakstu',
    'The requested file does not exist.' => 'Pieprasītais fails neeksistē',
    'The uploaded file does not exist.' => 'Augšuplādētais fails neeksistē',
    'UploadHandler mandatory option file_name is not set' => 'Nav norādīts obligāts parametrs file_name',
    'UploadHandler mandatory option model_id is not set' => 'Nav norādīts obligāts parametrs model_id',
    'UploadHandler mandatory option module_name is not set' => 'Nav norādīts obligāts parametrs module_name',
    'mandatory POST parameter model_name is not set' => 'Nav norādīts obligāts parametrs module_name',
    'upload_file is not set' => 'Nav norādīts pievienojamais fails',
    'Add' => 'Pievienot',
    'Add Datetime' => 'Pievienošanas datums',
    'Are you sure you want to delete this item?' => 'Vai tiešām vēlies dzēst?',
    'Attachments' => 'Pielikumi',
    'Close' => 'Aizvērt',
    'Delete' => 'Dzēst',
    'Deleted' => 'Dzēsts',
    'Download' => 'Lejuplādēt',
    'Drag&Drop a file here, upload will start automatically' => 'Ievelc šeit failu, augšupielāde sāksies automātiski',
    'Drag&Drop file here' => 'Ievelc failu šeit',
    'File Name' => 'Faila nosaukums',
    'File deleted' => 'Fails dzēsts',
    'Model ID' => 'Modeļa ID',
    'Model Name' => 'Modeļa nosaukums',
    'No results found.' => 'Ieraksti netika atrasti',
    'Notes' => 'Piezīmes',
    'Type ID' => 'Tips',
    'User ID' => 'Lietotāja ID',
];
