<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => '',
    'Add Datetime' => '',
    'Are you sure you want to delete this item?' => '',
    'Attachments' => '',
    'Close' => '',
    'Delete' => '',
    'Deleted' => '',
    'Download' => '',
    'Drag&Drop a file here, upload will start automatically' => '',
    'Drag&Drop file here' => '',
    'File Name' => '',
    'File deleted' => '',
    'File not uploaded.' => '',
    'Forbidden file type' => '',
    'ID' => '',
    'Insert DB record failed' => '',
    'Model ID' => '',
    'Model Name' => '',
    'No results found.' => '',
    'Notes' => '',
    'The requested file does not exist.' => '',
    'The uploaded file does not exist.' => '',
    'Type ID' => '',
    'UploadHandler mandatory option file_name is not set' => '',
    'UploadHandler mandatory option model_id is not set' => '',
    'UploadHandler mandatory option module_name is not set' => '',
    'User ID' => '',
    'mandatory POST parameter model_name is not set' => '',
    'upload_file is not set' => '',
];
